version: "3.9"

services:
  ui:
    image: expense_tracker_fe
    ports:
      - "5000:5000"
    environment: 
      EXPENSE_API: http://localhost:8001
  backend:
    image: expense_tracker_be
    ports:
      - "8001:8001"